---
################ Default config for all hosts ################
deployment_directory: "/home/{{ ansible_user_id }}/edumeet"

# branch https://github.com/edumeet/edumeet-docker
edumeet_branch: master
# docker tag https://hub.docker.com/r/edumeet/edumeet/
edumeet_tag: latest

# use the appropriate config templete
# set it to multiparty-meeting version
# or dev for develop
config_template_version: 3.2.1

fqdn_host: edumeetmanual02
fqdn_domain: uitdeknoei-hr.src.surf-hosted.nl

# let's encrypt
cert_domains:
  - "{{ fqdn_host }}.{{ fqdn_domain }}"
cert_email: "carsten.schelp@surf.nl"

# TURN
turn_uri: turn:ltc.turn.geant.org:443?transport=tcp
turn_user: carsten_schelp_at_surf_nl
turn_password: q9y72cUFKcSPUJDjNdJdJ5rDE2eHkjKV


# Introduced in version: 3.3.0
# If you part of the NREN community then
# goto https://turn.geant.org to get your api key.
turn_api_uri: "https://api.turn.geant.org/turn"
turn_api_key: ""

# session cookie secret
cookie_secret: 4cd461e3-b97c-45c2-accd-363470a0b77a

# Page head short title
title: "Multiparty Meeting"
#############################################


# Login using OIDC
login_enabled: 'false'
# OIDC op should support discovery!
issuer_url: "https://op.example.com"
client_id: id
client_secret: secret
redirect_uri: "https://meet.example.com/auth/callback"

# enable LTI 1.1 for Learning Management Systems like mooodle
lti_enabled: 'false'
lti_consumerKey: key
lti_consumerSecret: secret


# DEPRACATED if version >= 3.3.0

# If this is set to true, only signed-in users will be able
# to join a room directly. Non-signed-in users (guests) will
# always be put in the lobby regardless of room lock status.
# If false, there is no difference between guests and signed-in
# users when joining.
requireSignInToAccess: 'false'

# This flag has no effect when requireSignInToAccess is false
# When truthy, the room will be open to all users when the first
# authenticated user has already joined the room.
activateOnHostJoin: 'false'

# by default we use letsencrypt, set it true to enable local cert
local_cert: false
