---
# branch https://github.com/edumeet/edumeet-docker
edumeet_branch: master
# docker tag https://hub.docker.com/r/edumeet/edumeet/
edumeet_tag: 3.5.3

# use the appropriate config templete
# set it to multiparty-meeting version
# or dev for develop
config_template_version: 3.5.0

fqdn_domain: uitdeknoei-hr.src.surf-hosted.nl

# let's encrypt
cert_domains:
  - "{{ fqdn_host }}.{{ fqdn_domain }}"
cert_email: carsten.schelp@surf.nl

# TURN
turn_uri: turn:ltc.turn.geant.org:443?transport=tcp
turn_user: carsten_schelp_at_surf_nl
turn_password: {{ turn_password }}

# Introduced in version: 3.3.0
# If you part of the NREN community then
# goto https://turn.geant.org to get your api key.
turn_api_uri: "https://api.turn.geant.org/turn"
turn_api_key: ""

# session cookie secret
cookie_secret: {{ cookie_secret }}


# See for more options and defaults in all.yml
