# branch https://github.com/misi/mm
mm_branch: master
# docker tag https://hub.docker.com/r/misi/mm/
mm_tag: latest


fqdn_domain: example.com

# let's encrypt
cert_domains:
  - "{{ fqdn_host }}.{{ fqdn_domain }}"
cert_email: user@example.com

# TURN
turn_uri: turn:ltc.turn.geant.org:443?transport=tcp
turn_user: user
turn_password: password

# session cookie secret
cookie_secret: secret-cookie


#See for more options and defaults in all.yml

