---
- hosts: 
    - mm
    - mm-dev
  roles:
  - role: jnv.unattended-upgrades
    become: yes
    unattended_origins_patterns:
    - 'origin=Debian,codename=${distro_codename},label=Debian-Security' # security updates
    - 'o=Debian,codename=${distro_codename},label=Debian' # updates including non-security updates
    - 'o=Debian,codename=${distro_codename},a=proposed-updates'
    unattended_mail: "{{ unattended_email }}"

  - role: geerlingguy.docker
    become: yes

  - role: geerlingguy.certbot
    become: yes
    certbot_create_if_missing: true
    certbot_create_method: standalone
    certbot_admin_email: "{{ cert_email }}"
    # the role is dummy and needs anyway a service to stop, so I choosed: "ntp"
    certbot_create_standalone_stop_services: ntp
    certbot_certs:
     - domains: "{{ cert_domains }}"
  tasks:
  - name: Replace domain
    lineinfile:
      path: /etc/hosts
      regexp: '^(.*)novalocal(.*)$'
      line: '\1{{ main_domain }}\2'
      backrefs: yes

  # reload domain to ansible var
  - name: Setup
    setup:

  - name: Upgrade all packages to the latest version
    become: yes
    apt:
      name: "*"
      state: latest

  - name: Remove useless packages from the cache
    become: yes
    apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    become: yes
    apt:
      autoremove: yes

  - name: install packages
    become: yes
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    with_items:
      - git
      - vim
      - ferm
      - fail2ban

  - name: ferm config
    copy:
      src: ferm.conf
      dest: /etc/ferm/ferm.conf
    notify:
    - restart ferm

  - name: cleanup mm directory
    file:
      state: absent
      path: "mm"

  - name: docker clean mm container
    become: yes
    shell: "docker rm -f mm"
    ignore_errors: yes

  - name: git clone mm
    git:
      repo: 'https://github.com/misi/mm.git'
      dest: /home/debian/mm
      version: "{{ mm_branch }}"

  - name: Copy certs
    become: yes
    copy:
      src: "/etc/letsencrypt/live/{{ ansible_fqdn }}/{{ item }}"
      dest: "mm/certs/{{ item }}"
      remote_src: yes      
    with_items:
      - cert.pem
      - privkey.pem

  - name: copy logo
    copy:
      src: logo.svg
      dest: mm/logo/logo.svg

  - name: Setup turnserver uri
    lineinfile:
      path: "{{ item }}"
      backrefs: yes
      regexp: "^(.*)turn:example.com:443\\?transport=tcp(.*)$"
      line: '\1{{ turn_uri }}\2'
    with_items:
      - mm/configs/app/config.js
      - mm/configs/server/config.js

  - name: Setup turn user
    lineinfile:
      path: "{{ item }}"
      backrefs: yes
      regexp: "^(.*username.*)example(.*)$"
      line: '\1{{ turn_user }}\2'
    with_items:
      - mm/configs/app/config.js
      - mm/configs/server/config.js

  - name: Setup turn password
    lineinfile:
      path: "{{ item }}"
      backrefs: yes
      regexp: "^(.*credential.*)example(.*)$"
      line: '\1{{ turn_password }}\2'
    with_items:
      - mm/configs/app/config.js
      - mm/configs/server/config.js

  - name: Run mm container
    become: yes
    shell: ./run.sh
    args:
      chdir: "/home/{{ ansible_user }}/mm"
      executable: /bin/bash
  
  - name: Add cert renew hook.
    lineinfile:
      path: "/etc/letsencrypt/renewal/{{ ansible_fqdn }}.conf"      
      line: '{{ item }}'
      insertafter: '^\[renewalparams\]$'
      backup: yes
      backrefs: yes
    with_items:
      - "pre_hook = systemctl stop docker"
      - "post_hook = systemctl start docker"

  handlers:
  - name: restart ferm
    service:
      name: ferm
      state: restarted
